services:
  aix-docker:
    build: .
    container_name: aix-docker
    privileged: true
    devices:
      - /dev/net/tun
    ports:
      - "4441:4441"
    volumes:
      - ./images:/aix/images
    stdin_open: true
    tty: true
